# Generated by Django 2.1.5 on 2019-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('dbfId', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('playerClass', models.CharField(max_length=50)),
                ('cardSet_id', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
