# Generated by Django 2.1.5 on 2019-01-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='locale',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
